import http from 'node:http';
import { DatabaseSync } from 'node:sqlite';
import { randomBytes, scryptSync, timingSafeEqual, createHash } from 'node:crypto';
import { mkdirSync, readFileSync, existsSync, writeFileSync } from 'node:fs';
import { join, dirname, extname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
const ROOT=dirname(fileURLToPath(import.meta.url));
process.umask(0o077);
const DATA=resolve(process.env.DATA_DIR||join(ROOT,'data'));mkdirSync(DATA,{recursive:true,mode:0o700});
const sessions=new Map(), attempts=new Map();
const roles=['manager','reception','finance','housekeeping','dining','events','maintenance'];
const dbs=new Map();
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Maputo'}).format(new Date());
const dateAdd=(date,n)=>new Date(Date.parse(date+'T12:00:00Z')+n*86400000).toISOString().slice(0,10);
const id=()=>randomBytes(9).toString('hex');
function openDb(name){if(dbs.has(name))return dbs.get(name);const db=new DatabaseSync(name.startsWith('demo-')?':memory:':join(DATA,name+'.sqlite'));db.exec(`PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,name TEXT NOT NULL,email TEXT NOT NULL UNIQUE,password TEXT NOT NULL,role TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS rooms(id TEXT PRIMARY KEY,number TEXT NOT NULL UNIQUE,type TEXT NOT NULL,capacity INTEGER NOT NULL,rate INTEGER NOT NULL,cleaning TEXT NOT NULL DEFAULT 'clean',blocked INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS reservations(id TEXT PRIMARY KEY,guest TEXT NOT NULL,email TEXT,phone TEXT,company TEXT,room_id TEXT NOT NULL REFERENCES rooms(id),arrival TEXT NOT NULL,departure TEXT NOT NULL,adults INTEGER NOT NULL,rate INTEGER NOT NULL,status TEXT NOT NULL,source TEXT,notes TEXT,created TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS charges(id TEXT PRIMARY KEY,reservation_id TEXT NOT NULL REFERENCES reservations(id),description TEXT NOT NULL,department TEXT NOT NULL,amount INTEGER NOT NULL,created TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS payments(id TEXT PRIMARY KEY,reservation_id TEXT NOT NULL REFERENCES reservations(id),amount INTEGER NOT NULL,method TEXT NOT NULL,reference TEXT,created TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS venues(id TEXT PRIMARY KEY,name TEXT NOT NULL UNIQUE,capacity INTEGER NOT NULL,rate INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS events(id TEXT PRIMARY KEY,title TEXT NOT NULL,organiser TEXT NOT NULL,venue_id TEXT NOT NULL REFERENCES venues(id),start TEXT NOT NULL,end TEXT NOT NULL,attendees INTEGER NOT NULL,status TEXT NOT NULL,amount INTEGER NOT NULL,deposit INTEGER NOT NULL,notes TEXT);
CREATE TABLE IF NOT EXISTS tasks(id TEXT PRIMARY KEY,room_id TEXT REFERENCES rooms(id),title TEXT NOT NULL,priority TEXT NOT NULL,status TEXT NOT NULL,created TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS orders(id TEXT PRIMARY KEY,reservation_id TEXT REFERENCES reservations(id),outlet TEXT NOT NULL,description TEXT NOT NULL,amount INTEGER NOT NULL,settlement TEXT NOT NULL,created TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS audit(id TEXT PRIMARY KEY,actor TEXT NOT NULL,action TEXT NOT NULL,details TEXT NOT NULL,created TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS request_keys(key TEXT PRIMARY KEY,signature TEXT NOT NULL,status INTEGER NOT NULL,result TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS images(id TEXT PRIMARY KEY,title TEXT NOT NULL,url TEXT NOT NULL,category TEXT NOT NULL,alt TEXT NOT NULL,source TEXT,rights TEXT);
`);dbs.set(name,db);return db;}
const all=(db,sql,...args)=>db.prepare(sql).all(...args);
const one=(db,sql,...args)=>db.prepare(sql).get(...args);
const run=(db,sql,...args)=>db.prepare(sql).run(...args);
function tx(db,fn){db.exec('BEGIN IMMEDIATE');try{const r=fn();db.exec('COMMIT');return r;}catch(e){db.exec('ROLLBACK');throw e;}}
function requestKey(req,b){const key=req.headers['idempotency-key'];if(!key)return null;if(typeof key!=='string'||!/^[a-zA-Z0-9-]{8,100}$/.test(key))fail('Invalid request key.');return {key,signature:createHash('sha256').update(req.url+'|'+JSON.stringify(b)).digest('hex')};}
function transaction(db,req,b,status,result,fn){return tx(db,()=>{fn();const k=requestKey(req,b);if(k)run(db,'INSERT INTO request_keys VALUES(?,?,?,?)',k.key,k.signature,status,JSON.stringify(result));});}
function fail(message,status=400){const e=new Error(message);e.status=status;throw e;}
function text(v,label,max=500){if(typeof v!=='string'||!v.trim()||v.length>max)fail(`${label} is required (maximum ${max} characters).`);return v.trim();}
function optional(v,max=1000){if(v==null)return '';if(typeof v!=='string'||v.length>max)fail('Text value is too long.');return v.trim();}
function choice(v,values,label){if(!values.includes(v))fail(`Invalid ${label}.`);return v;}
function integer(v,label,min=0,max=100000000){if(!Number.isSafeInteger(v)||v<min||v>max)fail(`${label} must be between ${min} and ${max}.`);return v;}
function money(v,label='Amount',allowZero=false){if(typeof v!=='number'||!Number.isFinite(v)||v<(allowZero?0:0.01)||v>100000000)fail(`${label} must be a valid positive amount.`);return Math.round(v*100);}
function date(v){if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v)||!Number.isFinite(Date.parse(v))||new Date(v).toISOString().slice(0,10)!==v)fail('Enter a valid date.');return v;}
function datetime(v){if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(v)||!Number.isFinite(Date.parse(v+'+02:00')))fail('Enter a valid date and time.');date(v.slice(0,10));if(+v.slice(11,13)>23||+v.slice(14,16)>59)fail('Invalid time.');return v;}
function passwordHash(v){text(v,'Password',200);if(v.length<10)fail('Use a password with at least 10 characters.');const salt=randomBytes(16).toString('hex');return salt+':'+scryptSync(v,salt,64).toString('hex');}
function verify(v,encoded){try{const [salt,h]=encoded.split(':');return timingSafeEqual(Buffer.from(h,'hex'),scryptSync(v,salt,64));}catch{return false;}}
function audit(db,s,action,details){run(db,'INSERT INTO audit VALUES(?,?,?,?,?)',id(),s.name,action,JSON.stringify(details),new Date().toISOString());}
function auth(req){const token=req.headers.cookie?.split(';').map(x=>x.trim()).find(x=>x.startsWith('platinum_session='))?.split('=')[1];const s=sessions.get(token);if(!s||s.expiry<Date.now()){if(s?.demo){dbs.get(s.db)?.close();dbs.delete(s.db);}if(token)sessions.delete(token);fail('Please sign in to continue.',401);}const db=openDb(s.db);if(!s.demo){const u=one(db,'SELECT * FROM users WHERE id=? AND active=1',s.userId);if(!u)fail('This account is inactive.',401);s.role=u.role;s.name=u.name;}return s;}
function permit(s,allowed){if(!allowed.includes(s.role))fail('Your role does not permit this action.',403);}
const managers=['manager'];const front=['manager','reception'];const financial=['manager','finance','reception'];const guestAccess=['manager','reception','finance','events','dining'];
function createSession(res,user,db,demo=false){const token=randomBytes(32).toString('hex');const s={userId:user.id,name:user.name,role:user.role,db,demo,expiry:Date.now()+8*3600000};sessions.set(token,s);res.setHeader('Set-Cookie',`platinum_session=${token}; Path=/; HttpOnly; SameSite=Strict; Max-Age=28800${process.env.SECURE_COOKIE==='1'?'; Secure':''}`);return {user:{id:s.userId,name:s.name,role:s.role},demo};}
function json(res,status,data){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data));}
async function body(req){let raw='';for await(const chunk of req){raw+=chunk;if(raw.length>7*1024*1024)fail('Request is too large.',413);}try{return raw?JSON.parse(raw):{};}catch{fail('Invalid JSON.');}}
function reservation(db,rid){const r=one(db,'SELECT * FROM reservations WHERE id=?',rid);if(!r)fail('Reservation not found.',404);return r;}
function totals(db,rid){const charges=one(db,'SELECT COALESCE(SUM(amount),0) total FROM charges WHERE reservation_id=?',rid).total;const paid=one(db,'SELECT COALESCE(SUM(amount),0) total FROM payments WHERE reservation_id=?',rid).total;return {charges,paid,balance:charges-paid};}
function overlap(db,room,arrival,departure,exclude=''){return one(db,"SELECT id FROM reservations WHERE room_id=? AND status IN ('confirmed','checked-in') AND arrival<? AND departure>? AND id<>?",room,departure,arrival,exclude);}
function ensureRoom(db,roomId){const room=one(db,'SELECT * FROM rooms WHERE id=?',roomId);if(!room)fail('Room not found.',404);return room;}
function seedDemo(db){const now=today();run(db,'INSERT INTO users VALUES(?,?,?,?,?,1)','demo','Demo Manager','demo@example.test',passwordHash('not-a-real-login-123'),'manager');
for(let i=0;i<24;i++){const n=101+i;run(db,'INSERT INTO rooms VALUES(?,?,?,?,?,?,?)','room'+n,String(n),i<12?'Deluxe':i<20?'Executive':'Suite',i<20?2:3,(i<12?4800:i<20?6500:9200)*100,i===5||i===17?'dirty':'clean',i===23?1:0);}
const guests=['Ana Mucavele','Daniel Ferreira','Sofia Mendes','James Wilson','Celina Dlamini','Paulo Chissano','Grace Moyo','Maria Santos','David Nkosi','Isabel Machava'];
for(let i=0;i<10;i++){const rid='stay'+i,status=i<6?'checked-in':'confirmed',arr=i<6?dateAdd(now,-2):now,dep=i===2?now:dateAdd(now,2+i%3);const room=one(db,'SELECT * FROM rooms WHERE id=?','room'+(101+i));run(db,'INSERT INTO reservations VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)',rid,guests[i],guests[i].split(' ')[0].toLowerCase()+'@example.test','+258 84 000 0000',i%3===0?'Example Conference Group':'',room.id,arr,dep,2,room.rate,status,i%2?'Direct':'Corporate','Demonstration record',new Date().toISOString());run(db,'INSERT INTO charges VALUES(?,?,?,?,?,?)',id(),rid,'Accommodation · '+Math.round((Date.parse(dep)-Date.parse(arr))/86400000)+' nights','Rooms',room.rate*Math.round((Date.parse(dep)-Date.parse(arr))/86400000),new Date().toISOString());run(db,'INSERT INTO payments VALUES(?,?,?,?,?,?)',id(),rid,room.rate*(i===2?2:1),'Bank transfer','Demo deposit',new Date().toISOString());}
for(let i=1;i<=3;i++)run(db,'INSERT INTO venues VALUES(?,?,?,?)','venue'+i,['Acacia Hall','Platinum Ballroom','Boardroom'][i-1],[120,300,20][i-1],[25000,48000,12000][i-1]*100);
run(db,'INSERT INTO events VALUES(?,?,?,?,?,?,?,?,?,?,?)','event1','Leadership workshop','Example Business Group','venue1',now+'T09:00',now+'T17:00',80,'confirmed',2500000,1000000,'Projector, lunch, and two coffee breaks');
run(db,'INSERT INTO events VALUES(?,?,?,?,?,?,?,?,?,?,?)','event2','Celebration dinner','Example Events','venue2',dateAdd(now,2)+'T18:00',dateAdd(now,2)+'T23:00',150,'provisional',4800000,0,'Banquet setup');
run(db,'INSERT INTO tasks VALUES(?,?,?,?,?,?)','task1','room124','Inspect air conditioning','high','open',new Date().toISOString());
run(db,'INSERT INTO tasks VALUES(?,?,?,?,?,?)','task2','room118','Replace bedside lamp','normal','open',new Date().toISOString());
run(db,'INSERT INTO settings VALUES(?,?)','property_name','Platinum Lodge');run(db,'INSERT INTO settings VALUES(?,?)','address','Tchumene II, Matola, Mozambique');
loadReferenceImages(db);audit(db,{name:'System'},'Demo workspace created',{fictional:true});}
function loadReferenceImages(db){const file=join(ROOT,'assets/reference/image-manifest.json');if(existsSync(file)){for(const [i,x] of JSON.parse(readFileSync(file,'utf8')).entries()){run(db,'INSERT OR IGNORE INTO images VALUES(?,?,?,?,?,?,?)','reference'+i,x.title,x.image_url,/suite|bedroom/i.test(x.title)?'Rooms':/reception/i.test(x.title)?'Reception':'Facilities',x.alt_text,x.source_page,'Reference only; reuse permission unverified');}}}
function snapshot(db,s){const rooms=all(db,'SELECT * FROM rooms ORDER BY number');const venues=all(db,'SELECT * FROM venues ORDER BY name');const tasks=all(db,'SELECT t.*,r.number room_number FROM tasks t LEFT JOIN rooms r ON r.id=t.room_id ORDER BY t.created DESC');const settings=Object.fromEntries(all(db,'SELECT * FROM settings').map(x=>[x.key,x.value]));const images=all(db,'SELECT * FROM images ORDER BY rowid');const data={rooms,venues,tasks,settings,images,user:{id:s.userId,name:s.name,role:s.role},demo:s.demo,today:today()};
if(financial.includes(s.role)){data.reservations=all(db,`SELECT r.*,rm.number room_number,rm.type room_type,(SELECT COALESCE(SUM(amount),0) FROM charges WHERE reservation_id=r.id) charges,(SELECT COALESCE(SUM(amount),0) FROM payments WHERE reservation_id=r.id) paid FROM reservations r JOIN rooms rm ON rm.id=r.room_id ORDER BY r.arrival DESC`);data.events=all(db,'SELECT e.*,v.name venue_name FROM events e JOIN venues v ON v.id=e.venue_id ORDER BY e.start');}
if(s.role==='dining')data.reservations=all(db,"SELECT r.id,r.guest,r.room_id,r.arrival,r.departure,r.adults,r.status,rm.number room_number,rm.type room_type FROM reservations r JOIN rooms rm ON rm.id=r.room_id WHERE r.status='checked-in'");
if(s.role==='events')data.events=all(db,'SELECT e.*,v.name venue_name FROM events e JOIN venues v ON v.id=e.venue_id ORDER BY e.start');
if(financial.includes(s.role))data.payments=all(db,'SELECT p.*,r.guest FROM payments p JOIN reservations r ON r.id=p.reservation_id ORDER BY p.created DESC');
if(['manager','dining','finance'].includes(s.role))data.orders=all(db,'SELECT o.*,r.guest FROM orders o LEFT JOIN reservations r ON r.id=o.reservation_id ORDER BY o.created DESC');
if(s.role==='manager'){data.users=all(db,'SELECT id,name,email,role,active FROM users ORDER BY name');data.audit=all(db,'SELECT * FROM audit ORDER BY created DESC LIMIT 100');}
// Occupancy is operational data; guest identity is withheld from housekeeping and maintenance.
data.occupancy=all(db,"SELECT room_id,id reservation_id,departure FROM reservations WHERE status='checked-in'");return data;}
async function api(req,res,url){const method=req.method,path=url.pathname,b=method==='GET'?{}:await body(req);
if(path==='/api/bootstrap'&&method==='GET')return json(res,200,{needsSetup:one(openDb('hotel'),'SELECT COUNT(*) n FROM users').n===0});
if(path==='/api/setup'&&method==='POST'){const db=openDb('hotel');if(one(db,'SELECT COUNT(*) n FROM users').n)fail('The hotel account has already been created.',409);const user={id:id(),name:text(b.name,'Name',100),email:text(b.email,'Email',150).toLowerCase(),role:'manager'};if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(user.email))fail('Enter a valid email.');const hashed=passwordHash(b.password);tx(db,()=>{run(db,'INSERT INTO users VALUES(?,?,?,?,?,1)',user.id,user.name,user.email,hashed,user.role);run(db,'INSERT INTO settings VALUES(?,?)','property_name','Platinum Lodge');run(db,'INSERT INTO settings VALUES(?,?)','address','Tchumene II, Matola, Mozambique');loadReferenceImages(db);audit(db,user,'Hotel account created',{});});return json(res,201,createSession(res,user,'hotel'));}
if(path==='/api/login'&&method==='POST'){const key=req.socket.remoteAddress;const attempt=attempts.get(key)||{count:0,since:Date.now()};if(Date.now()-attempt.since>900000){attempt.count=0;attempt.since=Date.now();}if(attempt.count>=10)fail('Too many attempts. Try again in 15 minutes.',429);const db=openDb('hotel'),u=one(db,'SELECT * FROM users WHERE email=? AND active=1',optional(b.email).toLowerCase());if(!u||typeof b.password!=='string'||b.password.length>200||!verify(b.password,u.password)){attempt.count++;attempts.set(key,attempt);fail('Email or password is incorrect.',401);}attempts.delete(key);return json(res,200,createSession(res,u,'hotel'));}
if(path==='/api/demo'&&method==='POST'){const token='demo-'+id();const db=openDb(token);seedDemo(db);return json(res,201,createSession(res,{id:'demo',name:'Demo Manager',role:'manager'},token,true));}
if(path==='/api/logout'&&method==='POST'){const token=req.headers.cookie?.split(';').map(x=>x.trim()).find(x=>x.startsWith('platinum_session='))?.split('=')[1];const s=sessions.get(token);sessions.delete(token);if(s?.demo){dbs.get(s.db)?.close();dbs.delete(s.db);}res.setHeader('Set-Cookie','platinum_session=; Path=/; HttpOnly; SameSite=Strict; Max-Age=0');return json(res,200,{ok:true});}
const s=auth(req),db=openDb(s.db);
if(method==='POST'&&['/api/reservations','/api/payments','/api/charges','/api/refunds','/api/orders'].includes(path)){permit(s,path==='/api/reservations'?front:path==='/api/refunds'?managers:path==='/api/orders'?['manager','dining']:financial);const k=requestKey(req,b);if(k){const previous=one(db,'SELECT * FROM request_keys WHERE key=?',k.key);if(previous){if(previous.signature!==k.signature)fail('Request key was already used for a different transaction.',409);return json(res,previous.status,JSON.parse(previous.result));}}}
if(path==='/api/state'&&method==='GET')return json(res,200,snapshot(db,s));
if(path==='/api/reservations'&&method==='POST'){permit(s,front);const room=ensureRoom(db,b.room_id),arrival=date(b.arrival),departure=date(b.departure);if(departure<=arrival)fail('Departure must be after arrival.');if((Date.parse(departure)-Date.parse(arrival))/86400000>366)fail('A stay cannot exceed 366 nights.');integer(b.adults,'Guests',1,room.capacity);if(room.blocked)fail('This room is blocked for maintenance.',409);if(overlap(db,room.id,arrival,departure))fail('This room is already booked for these dates.',409);const rid=id(),rate=money(b.rate,'Nightly rate');const guest=text(b.guest,'Guest name',100);transaction(db,req,b,201,{id:rid},()=>{run(db,'INSERT INTO reservations VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)',rid,guest,optional(b.email,150),optional(b.phone,50),optional(b.company,150),room.id,arrival,departure,b.adults,rate,'confirmed',choice(b.source,['Direct','Corporate','Walk-in','Online'],'booking source'),optional(b.notes),new Date().toISOString());run(db,'INSERT INTO charges VALUES(?,?,?,?,?,?)',id(),rid,'Accommodation · '+Math.round((Date.parse(departure)-Date.parse(arrival))/86400000)+' nights','Rooms',rate*Math.round((Date.parse(departure)-Date.parse(arrival))/86400000),new Date().toISOString());audit(db,s,'Reservation created',{id:rid,room:room.number});});return json(res,201,{id:rid});}
let m=path.match(/^\/api\/reservations\/([^/]+)\/(status|folio)$/);
if(m&&m[2]==='folio'&&method==='GET'){permit(s,financial);const r=reservation(db,m[1]);return json(res,200,{...totals(db,r.id),reservation:r,room:ensureRoom(db,r.room_id),charges:all(db,'SELECT * FROM charges WHERE reservation_id=? ORDER BY created',r.id),payments:all(db,'SELECT * FROM payments WHERE reservation_id=? ORDER BY created',r.id)});}
if(m&&m[2]==='status'&&method==='POST'){permit(s,front);const r=reservation(db,m[1]),status=choice(b.status,['checked-in','checked-out','cancelled','no-show'],'status');const permitted={confirmed:['checked-in','cancelled','no-show'],'checked-in':['checked-out']};if(!permitted[r.status]?.includes(status))fail('This reservation cannot move to that status.',409);tx(db,()=>{if(status==='checked-in'){const room=ensureRoom(db,r.room_id);if(room.cleaning!=='clean'||room.blocked)fail('The room must be clean and unblocked before check-in.',409);if(r.arrival>today()||r.departure<=today())fail('Check-in must be within the booked stay dates.',409);if(one(db,"SELECT id FROM reservations WHERE room_id=? AND status='checked-in'",r.room_id))fail('Another guest is still checked into this room.',409);}if(status==='checked-out'){if(totals(db,r.id).balance>0)fail('Settle the outstanding balance before check-out.',409);run(db,"UPDATE rooms SET cleaning='dirty' WHERE id=?",r.room_id);}if(['cancelled','no-show'].includes(status)){const c=totals(db,r.id).charges;if(c)run(db,'INSERT INTO charges VALUES(?,?,?,?,?,?)',id(),r.id,'Booking charges reversed · '+status,'Adjustment',-c,new Date().toISOString());}run(db,'UPDATE reservations SET status=? WHERE id=?',status,r.id);audit(db,s,'Reservation '+status,{id:r.id});});return json(res,200,{ok:true});}
m=path.match(/^\/api\/reservations\/([^/]+)$/);if(m&&method==='PATCH'){permit(s,front);const r=reservation(db,m[1]);if(!['confirmed','checked-in'].includes(r.status))fail('Only active reservations can be amended.');const room=ensureRoom(db,b.room_id||r.room_id),arrival=b.arrival?date(b.arrival):r.arrival,departure=b.departure?date(b.departure):r.departure;if(departure<=arrival||(Date.parse(departure)-Date.parse(arrival))/86400000>366)fail('Enter a stay of 1 to 366 nights.');if(r.status==='checked-in'&&arrival!==r.arrival)fail('Arrival cannot change after check-in.');if(r.status==='checked-in'&&departure<=today())fail('Use check-out to complete this stay.');const adults=b.adults==null?r.adults:integer(b.adults,'Guests',1,room.capacity);if(adults>room.capacity)fail('The room does not have enough capacity.');if(room.blocked)fail('The room is blocked.',409);if(overlap(db,room.id,arrival,departure,r.id))fail('The room is booked for the requested dates.',409);if(r.status==='checked-in'&&room.id!==r.room_id&&(room.cleaning!=='clean'||one(db,"SELECT id FROM reservations WHERE room_id=? AND status='checked-in'",room.id)))fail('The new room must be clean and unoccupied.',409);tx(db,()=>{const oldNights=Math.round((Date.parse(r.departure)-Date.parse(r.arrival))/86400000),newNights=Math.round((Date.parse(departure)-Date.parse(arrival))/86400000);if(oldNights!==newNights)run(db,'INSERT INTO charges VALUES(?,?,?,?,?,?)',id(),r.id,'Stay amendment · '+(newNights-oldNights)+' nights','Rooms',(newNights-oldNights)*r.rate,new Date().toISOString());if(r.status==='checked-in'&&room.id!==r.room_id)run(db,"UPDATE rooms SET cleaning='dirty' WHERE id=?",r.room_id);run(db,'UPDATE reservations SET room_id=?,arrival=?,departure=?,adults=?,notes=? WHERE id=?',room.id,arrival,departure,adults,b.notes==null?r.notes:optional(b.notes),r.id);audit(db,s,'Reservation amended',{id:r.id,room:room.number,arrival,departure});});return json(res,200,{ok:true});}
if(path==='/api/charges'&&method==='POST'){permit(s,financial);const r=reservation(db,b.reservation_id);if(!['confirmed','checked-in'].includes(r.status))fail('Charges require an active reservation.');const amount=money(b.amount);const description=text(b.description,'Description',200);const department=choice(b.department,['Rooms','Dining','Events','Laundry','Other'],'department');transaction(db,req,b,201,{ok:true},()=>{run(db,'INSERT INTO charges VALUES(?,?,?,?,?,?)',id(),r.id,description,department,amount,new Date().toISOString());audit(db,s,'Charge posted',{reservation:r.id,amount,department});});return json(res,201,{ok:true});}
if(path==='/api/payments'&&method==='POST'){permit(s,financial);const r=reservation(db,b.reservation_id);const amount=money(b.amount),method=choice(b.method,['Cash','Card','Bank transfer','Mobile money'],'payment method');transaction(db,req,b,201,{ok:true},()=>{if(amount>Math.max(0,totals(db,r.id).balance))fail('Payment exceeds the outstanding balance.');run(db,'INSERT INTO payments VALUES(?,?,?,?,?,?)',id(),r.id,amount,method,optional(b.reference,200),new Date().toISOString());audit(db,s,'Payment recorded',{reservation:r.id,amount,method});});return json(res,201,{ok:true});}
if(path==='/api/refunds'&&method==='POST'){permit(s,managers);const r=reservation(db,b.reservation_id),amount=money(b.amount),reason=text(b.reason,'Refund reason',200);transaction(db,req,b,201,{ok:true},()=>{if(amount>totals(db,r.id).paid)fail('Refund exceeds payments received.');run(db,'INSERT INTO payments VALUES(?,?,?,?,?,?)',id(),r.id,-amount,'Refund',reason,new Date().toISOString());audit(db,s,'Refund recorded',{reservation:r.id,amount,reason});});return json(res,201,{ok:true});}
if(path==='/api/rooms'&&method==='POST'){permit(s,managers);const number=text(b.number,'Room number',20),type=text(b.type,'Room category',50);if(one(db,'SELECT id FROM rooms WHERE number=?',number))fail('Room number already exists.',409);run(db,'INSERT INTO rooms VALUES(?,?,?,?,?,?,0)',id(),number,type,integer(b.capacity,'Capacity',1,12),money(b.rate,'Rate'),'clean');audit(db,s,'Room created',{number});return json(res,201,{ok:true});}
m=path.match(/^\/api\/rooms\/([^/]+)$/);if(m&&method==='PATCH'){const room=ensureRoom(db,m[1]);tx(db,()=>{if(b.cleaning!=null){permit(s,['manager','housekeeping','reception']);choice(b.cleaning,['dirty','cleaning','inspection','clean'],'cleaning status');if(b.cleaning==='clean'&&s.role==='housekeeping')fail('Reception or a manager must approve the inspection.',403);}if(b.blocked!=null){permit(s,['manager','maintenance']);if(typeof b.blocked!=='boolean')fail('Invalid room block.');if(b.blocked&&one(db,"SELECT id FROM reservations WHERE room_id=? AND status IN ('confirmed','checked-in') AND departure>?",room.id,today()))fail('Reallocate active and future bookings before blocking this room.',409);}if(b.rate!=null){permit(s,managers);money(b.rate,'Rate');}if(b.cleaning!=null)run(db,'UPDATE rooms SET cleaning=? WHERE id=?',b.cleaning,room.id);if(b.blocked!=null)run(db,'UPDATE rooms SET blocked=? WHERE id=?',b.blocked?1:0,room.id);if(b.rate!=null)run(db,'UPDATE rooms SET rate=? WHERE id=?',money(b.rate,'Rate'),room.id);audit(db,s,'Room updated',{room:room.number,...b});});return json(res,200,{ok:true});}
if(path==='/api/venues'&&method==='POST'){permit(s,managers);const name=text(b.name,'Venue name',100);if(one(db,'SELECT id FROM venues WHERE name=?',name))fail('Venue already exists.',409);run(db,'INSERT INTO venues VALUES(?,?,?,?)',id(),name,integer(b.capacity,'Capacity',1,2000),money(b.rate,'Rate'));audit(db,s,'Venue created',{name});return json(res,201,{ok:true});}
if(path==='/api/events'&&method==='POST'){permit(s,['manager','events']);const venue=one(db,'SELECT * FROM venues WHERE id=?',b.venue_id);if(!venue)fail('Select an event venue.');const start=datetime(b.start),end=datetime(b.end);if(end<=start)fail('Event end must be after its start.');const attendees=integer(b.attendees,'Attendees',1,venue.capacity),status=choice(b.status,['provisional','confirmed'],'event status');if(one(db,"SELECT id FROM events WHERE venue_id=? AND status<>'cancelled' AND start<? AND end>?",venue.id,end,start))fail('The venue is booked during this time. Include setup and cleanup in the booking.',409);const amount=money(b.amount),deposit=money(b.deposit,'Deposit',true);if(deposit>amount)fail('Deposit exceeds the event total.');run(db,'INSERT INTO events VALUES(?,?,?,?,?,?,?,?,?,?,?)',id(),text(b.title,'Event name',150),text(b.organiser,'Organiser',150),venue.id,start,end,attendees,status,amount,deposit,optional(b.notes));audit(db,s,'Event booked',{venue:venue.name,start});return json(res,201,{ok:true});}
m=path.match(/^\/api\/events\/([^/]+)$/);if(m&&method==='PATCH'){permit(s,['manager','events']);const e=one(db,'SELECT * FROM events WHERE id=?',m[1]);if(!e)fail('Event not found.',404);if(e.status==='cancelled')fail('Cancelled events cannot be changed.');tx(db,()=>{if(b.status)choice(b.status,['confirmed','cancelled'],'event status');if(b.deposit!=null){const deposit=money(b.deposit,'Total deposit',true);if(deposit>e.amount||deposit<e.deposit)fail('New deposit must be between the existing deposit and event total.');}if(b.status)run(db,'UPDATE events SET status=? WHERE id=?',b.status,e.id);if(b.deposit!=null)run(db,'UPDATE events SET deposit=? WHERE id=?',money(b.deposit,'Total deposit',true),e.id);audit(db,s,'Event updated',{id:e.id,...b});});return json(res,200,{ok:true});}
if(path==='/api/tasks'&&method==='POST'){permit(s,['manager','maintenance','housekeeping','reception']);if(b.room_id)ensureRoom(db,b.room_id);run(db,'INSERT INTO tasks VALUES(?,?,?,?,?,?)',id(),b.room_id||null,text(b.title,'Issue',200),choice(b.priority,['normal','high','urgent'],'priority'),'open',new Date().toISOString());audit(db,s,'Maintenance issue reported',{title:b.title});return json(res,201,{ok:true});}
m=path.match(/^\/api\/tasks\/([^/]+)$/);if(m&&method==='PATCH'){permit(s,['manager','maintenance']);if(!one(db,'SELECT id FROM tasks WHERE id=?',m[1]))fail('Task not found.',404);run(db,'UPDATE tasks SET status=? WHERE id=?',choice(b.status,['open','in-progress','resolved'],'task status'),m[1]);audit(db,s,'Maintenance status updated',{id:m[1],status:b.status});return json(res,200,{ok:true});}
if(path==='/api/orders'&&method==='POST'){permit(s,['manager','dining']);const amount=money(b.amount),description=text(b.description,'Order description',200),settlement=choice(b.settlement,['Room charge','Cash','Card','Mobile money'],'settlement'),outlet=choice(b.outlet,['Restaurant','Bar','Poolside'],'outlet');let rid=null;if(settlement==='Room charge'){const r=reservation(db,b.reservation_id);if(r.status!=='checked-in')fail('Room charges require a checked-in guest.');rid=r.id;}transaction(db,req,b,201,{ok:true},()=>{run(db,'INSERT INTO orders VALUES(?,?,?,?,?,?,?)',id(),rid,outlet,description,amount,settlement,new Date().toISOString());if(rid)run(db,'INSERT INTO charges VALUES(?,?,?,?,?,?)',id(),rid,outlet+' · '+description,'Dining',amount,new Date().toISOString());audit(db,s,'Dining order recorded',{amount,outlet,settlement});});return json(res,201,{ok:true});}
if(path==='/api/users'&&method==='POST'){permit(s,managers);const email=text(b.email,'Email',150).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))fail('Enter a valid email.');if(one(db,'SELECT id FROM users WHERE email=?',email))fail('Email already exists.',409);const uid=id();run(db,'INSERT INTO users VALUES(?,?,?,?,?,1)',uid,text(b.name,'Name',100),email,passwordHash(b.password),choice(b.role,roles,'role'));audit(db,s,'Staff account created',{email,role:b.role});return json(res,201,{ok:true});}
m=path.match(/^\/api\/users\/([^/]+)$/);if(m&&method==='PATCH'){permit(s,managers);if(m[1]===s.userId)fail('You cannot deactivate your own account.');if(typeof b.active!=='boolean')fail('Invalid account status.');const u=one(db,'SELECT id FROM users WHERE id=?',m[1]);if(!u)fail('Staff member not found.',404);run(db,'UPDATE users SET active=? WHERE id=?',b.active?1:0,m[1]);audit(db,s,'Staff access updated',{id:m[1],active:b.active});return json(res,200,{ok:true});}
if(path==='/api/password'&&method==='POST'){if(s.demo)fail('Password changes are unavailable in the demo.');const u=one(db,'SELECT * FROM users WHERE id=?',s.userId);if(typeof b.current!=='string'||b.current.length>200||!verify(b.current,u.password))fail('Current password is incorrect.',403);const hashed=passwordHash(b.password);run(db,'UPDATE users SET password=? WHERE id=?',hashed,s.userId);for(const [token,session] of sessions)if(session.userId===s.userId&&session!==s)sessions.delete(token);audit(db,s,'Password changed',{});return json(res,200,{ok:true});}
if(path==='/api/settings'&&method==='PATCH'){permit(s,managers);for(const key of ['property_name','address','phone','email'])if(b[key]!=null)run(db,'INSERT INTO settings VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value',key,text(b[key],key,200));audit(db,s,'Property details updated',{});return json(res,200,{ok:true});}
if(path==='/api/images'&&method==='POST'){permit(s,managers);let imageUrl=optional(b.url,2000);if(b.file){const data=Buffer.from(b.file,'base64');if(data.length>4*1024*1024||data.length<12)fail('Image must be below 4 MB.');let extension;if(data[0]===0xff&&data[1]===0xd8&&data[2]===0xff)extension='.jpg';else if(data.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))extension='.png';else if(data.toString('ascii',0,4)==='RIFF'&&data.toString('ascii',8,12)==='WEBP')extension='.webp';else fail('Upload a JPEG, PNG, or WebP image.');const directory=join(DATA,'uploads');mkdirSync(directory,{recursive:true});const file=id()+extension;writeFileSync(join(directory,file),data);imageUrl='/uploads/'+file;}else{try{const parsed=new URL(imageUrl);if(parsed.protocol!=='https:')fail('Image URL must use HTTPS.');}catch{fail('Enter a valid HTTPS image URL.');}}run(db,'INSERT INTO images VALUES(?,?,?,?,?,?,?)',id(),text(b.title,'Image title',100),imageUrl,choice(b.category,['Rooms','Facilities','Reception','Events'],'category'),text(b.alt,'Alternative text',200),optional(b.source,2000),text(b.rights,'Permission status',200));audit(db,s,'Image added',{title:b.title});return json(res,201,{ok:true});}
m=path.match(/^\/api\/images\/([^/]+)$/);if(m&&method==='DELETE'){permit(s,managers);run(db,'DELETE FROM images WHERE id=?',m[1]);audit(db,s,'Image removed',{id:m[1]});return json(res,200,{ok:true});}
if(path==='/api/backup'&&method==='GET'){permit(s,managers);const backup={version:1,exported:new Date().toISOString(),demo:s.demo};for(const table of ['rooms','reservations','charges','payments','venues','events','tasks','orders','audit','settings','images'])backup[table]=all(db,'SELECT * FROM '+table);res.setHeader('Content-Disposition','attachment; filename="platinum-records-'+today()+'.json"');return json(res,200,backup);}
fail('Endpoint not found.',404);}
const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json','.jpg':'image/jpeg','.png':'image/png','.webp':'image/webp','.svg':'image/svg+xml'};
const cleanup=setInterval(()=>{for(const [token,s] of sessions)if(s.expiry<Date.now()){sessions.delete(token);if(s.demo){dbs.get(s.db)?.close();dbs.delete(s.db);}}},60000);cleanup.unref();
const server=http.createServer(async(req,res)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('X-Frame-Options','DENY');res.setHeader('Content-Security-Policy',"default-src 'self'; img-src 'self' https: data:; style-src 'self' 'unsafe-inline'; script-src 'self'; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'");try{const url=new URL(req.url,'http://localhost');if(url.pathname.startsWith('/api/')){if(!['GET','HEAD'].includes(req.method)){if(req.headers['x-platinum-request']!=='1')fail('Invalid request origin.',403);if(req.headers.origin&&new URL(req.headers.origin).host!==req.headers.host)fail('Invalid request origin.',403);if(!req.headers['content-type']?.startsWith('application/json'))fail('Use JSON requests.',415);}return await api(req,res,url);}if(req.method!=='GET')fail('Method not allowed.',405);let path;if(url.pathname.startsWith('/uploads/')){auth(req);path=resolve(DATA,'.'+url.pathname);if(!path.startsWith(join(DATA,'uploads')+'/'))fail('Not found.',404);}else{path=resolve(ROOT,'public','.'+(url.pathname==='/'?'/index.html':url.pathname));if(!path.startsWith(join(ROOT,'public')+'/'))fail('Not found.',404);}if(!existsSync(path))fail('Not found.',404);res.writeHead(200,{'Content-Type':mime[extname(path)]||'application/octet-stream','Cache-Control':'no-cache'});res.end(readFileSync(path));}catch(e){json(res,e.status||500,{error:e.status?e.message:'Something went wrong. Please try again.'});if(!e.status)console.error(e);}});
server.listen(Number(process.env.PORT||3000),process.env.HOST||'127.0.0.1',()=>console.log(`Platinum Lodge ready at http://${process.env.HOST||'127.0.0.1'}:${process.env.PORT||3000}`));
for(const signal of ['SIGTERM','SIGINT'])process.on(signal,()=>server.close(()=>{for(const db of dbs.values())db.close();process.exit(0);}));
